# Generated by Django 6.0.7 on 2026-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Prato')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('categoria', models.CharField(choices=[('Pizza', 'Pizza'), ('Lanche', 'Lanche'), ('Hambúrguer', 'Hambúrguer')], max_length=50, verbose_name='Categoria')),
                ('imagem_url', models.URLField(help_text='Link direto da foto do prato (ex:Unsplash)', max_length=500, verbose_name='URL da Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Exibir no Cardápio?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos do Cardápio',
                'ordering': ['nome'],
            },
        ),
    ]
