# Generated by Django 6.0.7 on 2026-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pratos/', verbose_name='Foto do Computador'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(help_text='Ex: Pizza, Lanche, Hambúrguer, Bebida, Vinho, Sobremesa, Porção...', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='OU URL da Imagem na Web'),
        ),
    ]
